# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
author: binarymash
title: binarymash
description: the random thoughts and doings of a professional code monkey
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.binarymash.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: binarymash
github_username:  binarymash
paginate:            10
lang: "en-GB"
logo: "/assets/images/logo.png"
social:
  name: binarymash
  links:
    - https://github.com/binarymash
    - https://stackoverflow.com/users/1671745/binarymash
    - https://www.linkedin.com/in/philip-wood-70b298a/
    - https://twitter.com/binarymash
twitter:
  username: binarymash


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate  
  - jekyll-feed
  - jekyll-sitemap  
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
